import { v4 as uuid } from 'uuid';
import { DeviceStatus, Device } from '../../models/Device';

export default [
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    groupId: 0,
    status: DeviceStatus.Offline,
    lastUpdate: new Date(),
    positionId: 0,
    phone: '698901563',
    model: '',
    contact: '',
    category: '',
    disabled: false,
  },
] as Device[];
